version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r lambda_function/requirements.txt -t lambda_function/
  build:
    commands:
      - echo Zipping Lambda function...
      - cd lambda_function
      - zip -r ../lambda.zip .
  post_build:
    commands:
      - echo Deploying to Lambda...
      - aws lambda update-function-code --function-name resizeImageLambda --zip-file fileb://lambda_function/lambda.zip


artifacts:
  files:
    - lambda.zip
